/**
 * A slide instruction for pitch glide during note playback.
 */
export interface Slide {
  /** Time offset in seconds from note start when the slide reaches its target */
  when: number;
  /** Pitch delta in semitones relative to the original note pitch */
  delta: number;
}

/**
 * A single AHDSR envelope stage as defined in an sf2-json zone.
 */
export interface AhdsrStage {
  /** Duration of this stage in seconds */
  duration: number;
  /** Target volume level for this stage (0.0 – 1.0) */
  volume: number;
}

/**
 * A single zone from an sf2-json preset.
 * Zones map a key/velocity range to a base64-encoded audio sample
 * and define its playback parameters.
 */
export interface Sf2Zone {
  /** Lowest MIDI note number this zone covers */
  keyRangeLow: number;
  /** Highest MIDI note number this zone covers */
  keyRangeHigh: number;
  /** Base64-encoded audio sample (decoded and cached as `buffer` after first use) */
  file?: string;
  /** Decoded AudioBuffer — populated automatically after first playback */
  buffer?: AudioBuffer;
  /** Original pitch of the sample in cents (e.g. 6000 = MIDI note 60) */
  originalPitch?: number;
  /** Coarse tuning offset in semitones */
  coarseTune?: number;
  /** Fine tuning offset in cents */
  fineTune?: number;
  /** Loop start point in samples */
  loopStart?: number;
  /** Loop end point in samples */
  loopEnd?: number;
  /** Sample rate of the audio data */
  sampleRate?: number;
  /** Delay in seconds before the sample begins playing */
  delay?: number;
  /** AHDSR envelope stages — defaults to a simple sustain if absent */
  ahdsr?: AhdsrStage[];
}

/**
 * An sf2-json preset object.
 * Compatible with presets generated by the `sf2-json` package.
 *
 * @see https://www.npmjs.com/package/sf2-json
 *
 * @example
 * // Loading a preset generated by sf2-json
 * import preset from './sf2-json/acoustic_grand_piano_ogg.js';
 * const player = new WebAudioFontPlayer(preset, audioCtx);
 */
export interface Sf2Preset {
  /** Array of zones that make up this preset */
  zones: Sf2Zone[];
}

/**
 * Handle returned by `queueWaveTable`, representing a scheduled note.
 * Extends GainNode with envelope-specific properties.
 */
export interface NoteEnvelope extends GainNode {
  /** AudioBufferSourceNode driving this note (null after note ends) */
  audioBufferSourceNode: AudioBufferSourceNode | null;
  /** AudioContext time when the note starts */
  when: number;
  /** Total duration of the scheduled audio in seconds */
  duration: number;
  /** MIDI pitch of the note */
  pitch: number;
  /** Base detune in cents used for pitch calculations */
  baseDetune: number;
  /**
   * Cancels and fades out this note.
   * @param force - If true, cuts off immediately (5ms fade). If false, applies a soft 20ms fade.
   */
  cancel(force?: boolean): void;
}

/**
 * An AudioNode-compatible compressor interface.
 * Pass an object with an `input` property to route the player output
 * through your own compressor or effects chain.
 */
export interface AudioCompressorNode {
  /** The AudioNode input to connect the player's output to */
  input: AudioNode;
}

/**
 * WebAudioFontPlayer — sample-based instrument player for the Web Audio API.
 *
 * Plays sf2-json presets (SoundFont 2 samples converted to JSON/base64)
 * with full MIDI controller support: volume (CC7), expression (CC11),
 * sustain pedal (CC64), and pitch bend.
 *
 * Compatible with presets from the `sf2-json` package.
 * @see https://www.npmjs.com/package/sf2-json
 *
 * @example
 * import WebAudioFontPlayer from 'webaudiofontplayer';
 * import preset from './presets/acoustic_grand_piano.js'; // sf2-json format
 *
 * const audioCtx = new AudioContext();
 * const player = new WebAudioFontPlayer(preset, audioCtx);
 *
 * // Play middle C for 2 seconds
 * player.queueWaveTable(audioCtx.currentTime, 60, 2.0, 0.7);
 */
export default class WebAudioFontPlayer {
  /**
   * Creates a new WebAudioFontPlayer instance.
   *
   * @param preset - An sf2-json preset object containing the instrument zones.
   * @param audioCtx - The Web Audio API AudioContext to use for playback.
   * @param compressor - Optional compressor or effects node to route audio through.
   *   If omitted, the player connects directly to `audioCtx.destination`.
   *
   * @example
   * // Without compressor
   * const player = new WebAudioFontPlayer(preset, audioCtx);
   *
   * // With a custom compressor
   * const player = new WebAudioFontPlayer(preset, audioCtx, myCompressor);
   */
  constructor(preset: Sf2Preset, audioCtx: AudioContext, compressor?: AudioCompressorNode | null);

  /**
   * The currently active sf2-json preset.
   * Assigning a new preset swaps the instrument immediately;
   * notes already playing will finish with the previous preset.
   */
  get preset(): Sf2Preset;
  set preset(preset: Sf2Preset);

  /**
   * Schedules a note to be played.
   *
   * @param when - AudioContext time (in seconds) when the note should start.
   *   Pass `audioCtx.currentTime` to play immediately.
   * @param pitch - MIDI note number (0–127). Fractional values are supported for microtonal use.
   * @param duration - Note duration in seconds.
   * @param volume - Note velocity/volume (0.0 – 1.0). Defaults to 0.5 if not provided.
   *   Internally capped at 0.8 to prevent clipping.
   * @param slides - Optional array of pitch glide instructions applied during playback.
   * @returns The NoteEnvelope handle, or `null` if no zone was found for the pitch
   *   or the sample has not yet been decoded.
   *
   * @example
   * // Simple note
   * const env = player.queueWaveTable(audioCtx.currentTime, 60, 1.0, 0.8);
   *
   * // Note with pitch slide (bend up 2 semitones over 0.5s)
   * const env = player.queueWaveTable(audioCtx.currentTime, 60, 1.0, 0.8, [
   *   { when: 0.5, delta: 2 }
   * ]);
   *
   * // Cancel the note early
   * env?.cancel();
   */
  queueWaveTable(
    when: number,
    pitch: number,
    duration: number,
    volume?: number,
    slides?: Slide[]
  ): NoteEnvelope | null;

  /**
   * Immediately silences all scheduled and playing notes.
   * Gain is set to near-zero and all envelope timers are cleared.
   */
  cancelQueue(): Promise<void>;

  /**
   * Returns whether the sustain pedal (CC64) is currently active.
   */
  isSustainActive(): boolean;

  /**
   * Registers a cancel callback to be called when the sustain pedal is released.
   * Used to implement sustain pedal hold behaviour: the note should not stop
   * until the pedal is released, at which point `cancelFn` will be invoked.
   *
   * @param cancelFn - Function to call when sustain is released.
   *
   * @example
   * const env = player.queueWaveTable(when, pitch, 9999, volume);
   * if (player.isSustainActive()) {
   *   player.registerSustainNote(() => env?.cancel());
   * }
   */
  registerSustainNote(cancelFn: () => void): void;

  /**
   * Applies a MIDI pitch bend to all currently playing notes and future notes.
   *
   * @param value - Raw 14-bit MIDI pitch bend value (0–16383).
   *   Center / no bend = 8192. The bend range is ±2 semitones.
   *
   * @example
   * // Full bend up
   * player.setPitchBend(16383);
   *
   * // Center (no bend)
   * player.setPitchBend(8192);
   */
  setPitchBend(value: number): void;

  /**
   * Processes a MIDI Control Change message.
   *
   * Supported controllers:
   * - **CC 7** — Channel Volume (0–127): controls the main gain node.
   * - **CC 11** — Expression (0–127): controls a secondary expression gain.
   * - **CC 64** — Sustain Pedal (≥64 = on): holds notes until pedal is released.
   *
   * @param number - MIDI CC number.
   * @param value - CC value (0–127).
   *
   * @example
   * player.setController(7, 100);   // Set volume
   * player.setController(11, 127);  // Full expression
   * player.setController(64, 127);  // Sustain on
   * player.setController(64, 0);    // Sustain off
   */
  setController(number: number, value: number): void;

  /**
   * Releases all Web Audio resources held by this player.
   * Stops all playing notes, disconnects all audio nodes, and clears internal state.
   * The instance must not be used after calling `close()`.
   */
  close(): void;
}